Mock objects which are not unsafe will now raise an AttributeError if an
attribute that matches the name of an existing assertion is accessed, e.g. ``called_once`` instead of ``assert_called_once``.
This is in addition to this already happening for accessing attributes with prefixes assert, assret, asert, aseert, and assrt.
