A :exc:`ValueError` is now raised when a negative value is passed to
:func:`readline.append_history_file`
