:c:func:`Py_FinalizeEx` cannot be called in a subinterpreter anymore.
